### ISSUE TITLE
Show different message when API request is pending

### ISSUE THREAD

**Issue by svekko** [Tomburgs/agloe#2]
At the moment when the API request is pending then `Looks like we couldn't find what you were looking for 🥴` message is shown to the user. I think that `Please wait, loading for results` etc. might be a more appropriate message to show.

**Comment by Tomburgs** [comment]
This is a good idea. It should be possible by getting the search stream to send an end event, but the tricky part is that it parses nodes asynchronously, so it needs to be more coordinated than it is right now.

If you're interested in picking this up, feel free, otherwise I'm closing this issue for now, as it's not crucial.
